### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by 1stScience** [annalisetarhan/KacaOlur#1]
Do you have a product available in the Playstore?

**Comment by annalisetarhan** [comment]
Not related to this project, no

**Comment by 1stScience** [comment]
Can we try it?

**Comment by annalisetarhan** [comment]
You're welcome to do whatever you like with it, but beware! It's a very long way from production ready.

**Comment by 1stScience** [comment]
I had an MVP built using Kotlin through a team in India. You can find it on
the Playstore as YawaSOS, hence my interest.

Still trying to further develop it. The
Is opened me up to the whole NG 911 and location based services.

Sincerely,


Idua Olunwa
